name: Example PR Workflow
on:
  merge_group:
    types: [checks_requested]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for XXYYZZ
        run: grep -q XXYYZZ README.md

